#!/bin/bash
username=foo
f_name=bar
l_name=baz
password=fubar
email=notanemail@g.google

update_id=3

echo -e "Creating a user..."
curl --data "username=$username&f_name=$f_name&l_name=$l_name&password=$password&email=$email" localhost:8000/api/v1/users/create

echo -e "\n\nUpdating user with id=$update_id..."
curl --data "username=1afds&email=123@123.com" localhost:8000/api/v1/users/update/$update_id

echo -e "\n"
